//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VModer.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VModer.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内阁.
        /// </summary>
        public static string Character_advisor {
            get {
                return ResourceManager.GetString("Character.advisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类别.
        /// </summary>
        public static string Character_advisor_slot {
            get {
                return ResourceManager.GetString("Character.advisor_slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将军.
        /// </summary>
        public static string Character_corps_commander {
            get {
                return ResourceManager.GetString("Character.corps_commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 领导人.
        /// </summary>
        public static string Character_country_leader {
            get {
                return ResourceManager.GetString("Character.country_leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 元帅.
        /// </summary>
        public static string Character_field_marshal {
            get {
                return ResourceManager.GetString("Character.field_marshal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 海军指挥官.
        /// </summary>
        public static string Character_navy_leader {
            get {
                return ResourceManager.GetString("Character.navy_leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 意识形态.
        /// </summary>
        public static string Ideology {
            get {
                return ResourceManager.GetString("Ideology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缺失目标国家:.
        /// </summary>
        public static string MissingTargetCountry {
            get {
                return ResourceManager.GetString("MissingTargetCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特质.
        /// </summary>
        public static string Traits {
            get {
                return ResourceManager.GetString("Traits", resourceCulture);
            }
        }
    }
}
