//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace VModer.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VModer.Languages.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 未使用的语句 的本地化字符串。
        /// </summary>
        public static string Analyzer_UnusedStatement {
            get {
                return ResourceManager.GetString("Analyzer.UnusedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别: 的本地化字符串。
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内阁 的本地化字符串。
        /// </summary>
        public static string Character_advisor {
            get {
                return ResourceManager.GetString("Character.advisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别 的本地化字符串。
        /// </summary>
        public static string Character_advisor_slot {
            get {
                return ResourceManager.GetString("Character.advisor_slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将军 的本地化字符串。
        /// </summary>
        public static string Character_corps_commander {
            get {
                return ResourceManager.GetString("Character.corps_commander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 领导人 的本地化字符串。
        /// </summary>
        public static string Character_country_leader {
            get {
                return ResourceManager.GetString("Character.country_leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 元帅 的本地化字符串。
        /// </summary>
        public static string Character_field_marshal {
            get {
                return ResourceManager.GetString("Character.field_marshal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海军指挥官 的本地化字符串。
        /// </summary>
        public static string Character_navy_leader {
            get {
                return ResourceManager.GetString("Character.navy_leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理成功 的本地化字符串。
        /// </summary>
        public static string CleanupSuccessful {
            get {
                return ResourceManager.GetString("CleanupSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用装备模块: 的本地化字符串。
        /// </summary>
        public static string EnableEquipmentModules {
            get {
                return ResourceManager.GetString("EnableEquipmentModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建筑 {0} 等级超过上限, 最大值为: {1} 的本地化字符串。
        /// </summary>
        public static string ErrorMessage_BuildingLevelExceedsMaxValue {
            get {
                return ResourceManager.GetString("ErrorMessage.BuildingLevelExceedsMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的属性 {1} 超过最大值 {2} 的本地化字符串。
        /// </summary>
        public static string ErrorMessage_SkillExceedsMaxValue {
            get {
                return ResourceManager.GetString("ErrorMessage.SkillExceedsMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定义的胜利点 {0} 不在这个 State 中 的本地化字符串。
        /// </summary>
        public static string ErrorMessage_VictoryPointProvinceNotInState {
            get {
                return ResourceManager.GetString("ErrorMessage.VictoryPointProvinceNotInState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修复所有:  的本地化字符串。
        /// </summary>
        public static string FixAll {
            get {
                return ResourceManager.GetString("FixAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意识形态 的本地化字符串。
        /// </summary>
        public static string Ideology {
            get {
                return ResourceManager.GetString("Ideology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺失目标国家: 的本地化字符串。
        /// </summary>
        public static string MissingTargetCountry {
            get {
                return ResourceManager.GetString("MissingTargetCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到对应的 State 文件中 的本地化字符串。
        /// </summary>
        public static string QuickFix_MoveVictoryPointsToOccupiedStateFile {
            get {
                return ResourceManager.GetString("QuickFix.MoveVictoryPointsToOccupiedStateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除未使用的语句 的本地化字符串。
        /// </summary>
        public static string QuickFix_RemoveUnusedStatement {
            get {
                return ResourceManager.GetString("QuickFix.RemoveUnusedStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特质 的本地化字符串。
        /// </summary>
        public static string Traits {
            get {
                return ResourceManager.GetString("Traits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 经验值系数 的本地化字符串。
        /// </summary>
        public static string TraitXpFactor {
            get {
                return ResourceManager.GetString("TraitXpFactor", resourceCulture);
            }
        }
    }
}
